version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '4306:4306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec pumactl start
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
      - sockets:/myapp/tmp/sockets
    privileged: true
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - sockets:/myapp/tmp/sockets
    depends_on: 
      - app
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  sockets: